#!/usr/bin/env node
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as catalogModule from "@minecraft-skills/catalog";
import {
  getCatalog,
  getDataManifest,
  getDatapackSchemaSurface,
  getPaperApiSurface,
  getPaperPluginData,
  getVersionDetail,
  listAuthoringChecklists,
  listAuthoringDiagnostics,
  listAuthoringGuardrails,
  listAuthoringRecipes,
  listAuthoringScenarios,
  listClaimPolicies,
  listDomains,
  listFactSurfaces,
  listIntentLookups,
  listOutputRequirements,
  listReferences,
  listResponsePatterns,
  listVersions,
  validatePackFileContent,
} from "@minecraft-skills/catalog";
import { auditCurrentSources } from "./currentSources.js";
import { ingestDatapackSchemaSurfaces } from "./datapackSchemaSurfaceSummaries.js";
import {
  buildObservedDatapackSchemaSurface,
  writeObservedDatapackSchemaSurface,
} from "./datapackSchemaSurfaces.js";
import { buildJavaVersionIndex } from "./javaManifest.js";
import { ingestJavaReportSummaries, listPendingJavaReportVersions } from "./javaReportSummaries.js";
import {
  buildJavaReportsSummary,
  generateJavaReports,
  writeJavaReportsSummary,
} from "./javaReports.js";
import { buildJavaVersionDetail } from "./javaVersionDetail.js";
import { ingestJavaVersionDetails } from "./javaVersionDetails.js";
import { runPackageSmoke } from "./packageSmoke.js";
import { ingestPaperApiIndexes } from "./paperApiIndexes.js";
import { ingestPaperApiSurfaces } from "./paperApiSurfaces.js";
import { ingestPaperBuilds } from "./paperBuilds.js";
import { buildPaperPluginData } from "./paperProject.js";
import { ingestResourcepackModelSummaries } from "./resourcepackModelSummaries.js";
import { buildResourcepackModelSummary } from "./resourcepackModels.js";
import { ingestVanillaInventories } from "./vanillaInventories.js";
import { buildVanillaData, type VanillaPathIndex } from "./vanillaInventory.js";

type ValidationResult = {
  ok: boolean;
  messages: string[];
};

const generatedHeader = "<!-- generated by @minecraft-skills/maintainer; do not edit directly -->";

function isDirectRun(metaUrl: string): boolean {
  return process.argv[1]
    ? realpathSync(fileURLToPath(metaUrl)) === realpathSync(process.argv[1])
    : false;
}

function findRepositoryRoot(start = process.cwd()): string {
  let current = start;
  while (true) {
    if (existsSync(join(current, "pnpm-workspace.yaml"))) {
      return current;
    }
    const parent = dirname(current);
    if (parent === current) {
      throw new Error("Could not find repository root from current working directory");
    }
    current = parent;
  }
}

function requireFile(root: string, path: string, messages: string[]): void {
  if (!existsSync(join(root, path))) {
    messages.push(`missing file: ${path}`);
  }
}

function dataFilePath(path: string): string {
  return `packages/data/data/${path}`;
}

function requireDataFile(root: string, path: string, messages: string[]): void {
  requireFile(root, dataFilePath(path), messages);
}

function readJsonFile<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

function versionFromJsonFileName(file: string): string | undefined {
  return file.endsWith(".json") ? file.slice(0, -".json".length) : undefined;
}

function buildDataManifestEntries(root: string, baseUrl: string): DataManifestEntry[] {
  const dataRoot = join(root, "packages/data/data");
  const sections: Array<{
    directory: string;
    kind: DataManifestEntry["kind"];
  }> = [
    {
      directory: "java/datapack-schema-surfaces",
      kind: "datapack-schema-surface",
    },
    {
      directory: "java/paper-api-surfaces",
      kind: "paper-api-surface",
    },
    {
      directory: "java/resourcepack-models",
      kind: "resourcepack-model-summary",
    },
  ];
  const normalizedBaseUrl = baseUrl.replace(/\/+$/, "");
  const entries: DataManifestEntry[] = [];

  for (const section of sections) {
    const absoluteDirectory = join(dataRoot, section.directory);
    if (!existsSync(absoluteDirectory)) {
      continue;
    }
    for (const file of readdirSync(absoluteDirectory).sort((left, right) =>
      left.localeCompare(right, undefined, { numeric: true }),
    )) {
      const version = versionFromJsonFileName(file);
      if (!version) {
        continue;
      }
      const path = `${section.directory}/${file}`;
      const absolutePath = join(dataRoot, path);
      entries.push({
        path,
        kind: section.kind,
        edition: "java",
        version,
        size: statSync(absolutePath).size,
        sha256: sha256File(absolutePath),
        url: `${normalizedBaseUrl}/${path}`,
      });
    }
  }

  return entries;
}

function writeDataManifest(root: string, dataVersion?: string, baseUrl?: string): string {
  const current = getDataManifest();
  const manifestBaseUrl = baseUrl ?? current.defaultBaseUrl;
  const manifest = {
    schemaVersion: 1,
    dataVersion: dataVersion ?? current.dataVersion,
    defaultBaseUrl: manifestBaseUrl,
    cache: current.cache,
    downloadable: buildDataManifestEntries(root, manifestBaseUrl),
  };
  const output = join(root, dataFilePath("data-manifest.json"));
  writeFileSync(output, `${JSON.stringify(manifest, null, 2)}\n`);
  return output;
}

function isSafeRelativePath(path: string): boolean {
  return path.length > 0 && !path.includes("\0") && !path.split(/[\\/]/).includes("..");
}

function requireDataManifestIntegrity(root: string, messages: string[]): void {
  requireDataFile(root, "data-manifest.json", messages);
  const manifestPath = join(root, dataFilePath("data-manifest.json"));
  if (!existsSync(manifestPath)) {
    return;
  }

  const manifest = getDataManifest();
  if (manifest.schemaVersion !== 1) {
    messages.push("data manifest schemaVersion must be 1");
  }
  if (manifest.cache.environmentVariable !== "MINECRAFT_SKILLS_CACHE_DIR") {
    messages.push("data manifest cache environment variable must be MINECRAFT_SKILLS_CACHE_DIR");
  }

  const seenPaths = new Set<string>();
  for (const entry of manifest.downloadable) {
    const prefix = `data manifest entry ${entry.path}`;
    if (!isSafeRelativePath(entry.path)) {
      messages.push(`${prefix} must use a safe relative path`);
      continue;
    }
    if (seenPaths.has(entry.path)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    seenPaths.add(entry.path);

    if (entry.kind === "datapack-schema-surface") {
      if (entry.edition !== "java" || !entry.version) {
        messages.push(`${prefix} datapack schema surface must identify Java version`);
      } else if (entry.path !== `java/datapack-schema-surfaces/${entry.version}.json`) {
        messages.push(`${prefix} datapack schema surface path must match version`);
      }
    } else if (entry.kind === "paper-api-surface") {
      if (entry.edition !== "java" || !entry.version) {
        messages.push(`${prefix} Paper API surface must identify Java version`);
      } else if (entry.path !== `java/paper-api-surfaces/${entry.version}.json`) {
        messages.push(`${prefix} Paper API surface path must match version`);
      } else {
        const surface = readJsonFile<{
          typeCount?: unknown;
          memberCount?: unknown;
        }>(join(root, dataFilePath(entry.path)));
        if (surface.typeCount === 0 && surface.memberCount === 0) {
          messages.push(`${prefix} Paper API surface must not be empty`);
        }
      }
    } else if (entry.kind === "resourcepack-model-summary") {
      if (entry.edition !== "java" || !entry.version) {
        messages.push(`${prefix} resourcepack model summary must identify Java version`);
      } else if (entry.path !== `java/resourcepack-models/${entry.version}.json`) {
        messages.push(`${prefix} resourcepack model summary path must match version`);
      }
    } else {
      messages.push(`${prefix} has unsupported downloadable kind: ${entry.kind}`);
    }

    try {
      new URL(entry.url);
    } catch {
      messages.push(`${prefix} must include a valid URL`);
    }

    const absolutePath = join(root, dataFilePath(entry.path));
    requireDataFile(root, entry.path, messages);
    if (!existsSync(absolutePath)) {
      continue;
    }
    const actualSize = statSync(absolutePath).size;
    if (actualSize !== entry.size) {
      messages.push(
        `${prefix} size must match checked-in file: expected ${entry.size}, got ${actualSize}`,
      );
    }
    const actualSha256 = sha256File(absolutePath);
    if (actualSha256 !== entry.sha256) {
      messages.push(
        `${prefix} sha256 must match checked-in file: expected ${entry.sha256}, got ${actualSha256}`,
      );
    }
  }
}

function walkTextFiles(root: string, directory: string, files: string[] = []): string[] {
  const absoluteDirectory = join(root, directory);
  if (!existsSync(absoluteDirectory)) {
    return files;
  }
  for (const entry of readdirSync(absoluteDirectory)) {
    const path = join(directory, entry);
    const absolutePath = join(root, path);
    const stat = statSync(absolutePath);
    if (stat.isDirectory()) {
      if (
        path === ".git" ||
        path === "node_modules" ||
        path.endsWith("/dist") ||
        path === "packages/data/data/java"
      ) {
        continue;
      }
      walkTextFiles(root, path, files);
    } else if (/\.(?:md|json|ts|yaml|yml)$/.test(entry)) {
      files.push(path);
    }
  }
  return files;
}

function requireSourcePolicyIntegrity(root: string, messages: string[]): void {
  const sourcePolicy = getCatalog().sourcePolicy;
  if (sourcePolicy.minecraftWikiAutomation !== "forbidden") {
    messages.push("source policy must forbid Minecraft Wiki automation");
  }
  if (
    !sourcePolicy.prohibitedAutomation.some((rule) =>
      rule.includes("Do not fetch, crawl, summarize, or cite Minecraft Wiki pages"),
    )
  ) {
    messages.push("source policy must explicitly prohibit AI use of Minecraft Wiki pages");
  }
  for (const domain of getCatalog().domains) {
    for (const source of domain.primarySources) {
      if (source.url.includes("minecraft.wiki") || source.id.includes("minecraft-wiki")) {
        messages.push(`domain ${domain.id} must not expose Minecraft Wiki as a primary source`);
      }
      if (source.kind === "community-navigation") {
        messages.push(`domain ${domain.id} must not use community-navigation source kind`);
      }
    }
  }

  const requiredDatasetIds = new Set([
    "prismarinejs-minecraft-data",
    "prismarinejs-minecraft-assets",
    "inventivetalentdev-minecraft-assets",
    "misode-mcmeta",
  ]);
  const actualDatasetIds = new Set(
    sourcePolicy.recommendedCommunityDatasets.map((dataset) => dataset.id),
  );
  for (const id of requiredDatasetIds) {
    if (!actualDatasetIds.has(id)) {
      messages.push(`source policy must list recommended community dataset: ${id}`);
    }
  }

  const forbiddenPatterns = [
    /https?:\/\/(?:www\.)?minecraft\.wiki\b/i,
    /\bminecraft-wiki-(?:datapack|resourcepack|source|wiki)\b/i,
    /\bcommunity-navigation\b/i,
    /Minecraft Wiki may be used/i,
    /Use Minecraft Wiki (?!is human-only|pages are human-only)/i,
    /Minecraft Wiki is used only for/i,
    /navigation and provenance/i,
  ];
  for (const path of walkTextFiles(root, ".")) {
    if (path === "docs/SOURCE_STRATEGY.md" || path === "packages/maintainer/src/cli.ts") {
      continue;
    }
    const content = readFileSync(join(root, path), "utf8");
    for (const pattern of forbiddenPatterns) {
      if (pattern.test(content)) {
        messages.push(`forbidden Minecraft Wiki source wording in ${path}: ${pattern}`);
      }
    }
  }
}

function requireDocumentationIntegrity(root: string, messages: string[]): void {
  const packageJson = readJsonFile<{ version: string }>(join(root, "package.json"));
  const versionSupport = readFileSync(join(root, "docs/VERSION_SUPPORT.md"), "utf8");
  if (!versionSupport.includes(`minecraft-skills ${packageJson.version}`)) {
    messages.push("docs/VERSION_SUPPORT.md must reference the current workspace version");
  }

  const forbiddenSkillEntrypointPatterns = [
    /\bMCP\b/,
    /\bmcp\b/,
    /\bPackage API\b/,
    /\bpackage API\b/,
    /@minecraft-skills\/catalog/,
    /@minecraft-skills\/mcp/,
    /\b(?:get|list|search|compare)_[a-z_]+\b/,
  ];
  for (const domain of listDomains()) {
    const paths = [`skills/${domain.skill}/SKILL.md`];
    for (const reference of listReferences().filter((entry) => entry.domain === domain.id)) {
      paths.push(reference.path);
    }
    for (const path of paths) {
      const content = readFileSync(join(root, dataFilePath(path)), "utf8");
      for (const pattern of forbiddenSkillEntrypointPatterns) {
        if (pattern.test(content)) {
          messages.push(`skill-facing file must only document CLI entrypoints: ${path}`);
          break;
        }
      }
    }
  }
}

type PublicEntrypoints = {
  cliCommands: Set<string>;
  mcpTools: Set<string>;
  packageApis: Set<string>;
};

type DataManifestEntry = {
  path: string;
  kind: "datapack-schema-surface" | "paper-api-surface" | "resourcepack-model-summary";
  edition: "java";
  version: string;
  size: number;
  sha256: string;
  url: string;
};

function collectPublicEntrypoints(root: string): PublicEntrypoints {
  const cliSource = readFileSync(join(root, "packages/cli/src/cli.ts"), "utf8");
  const cliCommands = new Set([
    ...[...cliSource.matchAll(/command === "([^"]+)"/g)].map((match) => match[1] ?? ""),
    ...[...cliSource.matchAll(/"([^"]+ [^"]+)": "[^"]+"/g)].map((match) => match[1] ?? ""),
    ...[...cliSource.matchAll(/groupedCommand === "([^"]+)"/g)].map((match) => match[1] ?? ""),
  ]);
  const authoringSubcommands = [
    "context",
    "preflight",
    "evidence",
    "checklists",
    "checklist",
    "recipes",
    "recipe",
    "search-scenarios",
    "scenario-search",
    "scenarios",
    "scenario",
    "plan",
    "guardrails",
    "guardrail",
    "diagnostics",
    "diagnostic",
    "intents",
    "intent",
    "fact-surfaces",
    "fact-surface",
    "claim-policies",
    "claim-policy",
    "output-requirements",
    "output-requirement",
    "response-patterns",
    "response-pattern",
  ];
  for (const group of ["datapack", "resourcepack"]) {
    for (const subcommand of authoringSubcommands) {
      cliCommands.add(`${group} ${subcommand}`);
    }
  }
  for (const subcommand of authoringSubcommands) {
    cliCommands.add(`plugin paper ${subcommand}`);
  }
  for (const subcommand of [
    "info",
    "api",
    "api-index",
    "compare-api",
    "api-surface",
    "types",
    "members",
    "compare-api-surface",
    "events",
  ]) {
    cliCommands.add(`plugin paper ${subcommand}`);
  }
  const mcpTools = new Set(
    [
      ...readFileSync(join(root, "packages/mcp/src/tools.ts"), "utf8").matchAll(/name: "([^"]+)"/g),
    ].map((match) => match[1] ?? ""),
  );
  const packageApis = new Set(Object.keys(catalogModule));
  return {
    cliCommands,
    mcpTools,
    packageApis,
  };
}

function requirePublicEntrypoints(
  prefix: string,
  entrypoints: {
    cli: string[];
    mcp: string[];
    packageApis: string[];
  },
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  for (const command of entrypoints.cli) {
    if (!publicEntrypoints.cliCommands.has(command)) {
      messages.push(`${prefix} references missing CLI command: ${command}`);
    }
  }
  for (const tool of entrypoints.mcp) {
    if (!publicEntrypoints.mcpTools.has(tool)) {
      messages.push(`${prefix} references missing MCP tool: ${tool}`);
    }
  }
  for (const api of entrypoints.packageApis) {
    if (!publicEntrypoints.packageApis.has(api)) {
      messages.push(`${prefix} references missing package API: ${api}`);
    }
  }
}

function requireFactSurfaces(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "fact-surfaces.json", messages);
  const ids = new Set<string>();
  for (const surface of listFactSurfaces()) {
    const prefix = `fact surface ${surface.id}`;
    if (ids.has(surface.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(surface.id);
    if (surface.guarantees.length === 0) {
      messages.push(`${prefix} must list at least one guarantee`);
    }
    if (surface.nonGuarantees.length === 0) {
      messages.push(`${prefix} must list at least one non-guarantee`);
    }
    if (surface.cli.length === 0 && surface.mcp.length === 0 && surface.packageApis.length === 0) {
      messages.push(`${prefix} must expose at least one CLI, MCP, or package API entrypoint`);
    }
    requirePublicEntrypoints(prefix, surface, publicEntrypoints, messages);
  }
}

function requireAuthoringChecklists(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "authoring-checklists.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const seenDomains = new Set<string>();
  for (const checklist of listAuthoringChecklists()) {
    const prefix = `authoring checklist ${checklist.domain}`;
    if (!domains.has(checklist.domain)) {
      messages.push(`${prefix} must reference a catalog domain`);
    }
    if (seenDomains.has(checklist.domain)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    seenDomains.add(checklist.domain);
    if (checklist.steps.length === 0) {
      messages.push(`${prefix} must list at least one step`);
    }
    const stepIds = new Set<string>();
    for (const step of checklist.steps) {
      const stepPrefix = `${prefix} step ${step.id}`;
      if (stepIds.has(step.id)) {
        messages.push(`${stepPrefix} must not be duplicated`);
      }
      stepIds.add(step.id);
      if (step.evidence.length === 0) {
        messages.push(`${stepPrefix} must list evidence expectations`);
      }
      if (!step.failureMode) {
        messages.push(`${stepPrefix} must describe a failure mode`);
      }
      if (
        step.tools.cli.length === 0 &&
        step.tools.mcp.length === 0 &&
        step.tools.packageApis.length === 0
      ) {
        messages.push(`${stepPrefix} must expose at least one CLI, MCP, or package API entrypoint`);
      }
      requirePublicEntrypoints(stepPrefix, step.tools, publicEntrypoints, messages);
    }
  }
  for (const domain of domains) {
    if (!seenDomains.has(domain)) {
      messages.push(`missing authoring checklist for domain: ${domain}`);
    }
  }
}

function requireAuthoringDomains(
  prefix: string,
  recordDomains: readonly string[],
  catalogDomains: ReadonlySet<string>,
  messages: string[],
): void {
  // An empty list marks catalog-only, domain-neutral guidance rather than an authoring context.
  for (const domain of recordDomains) {
    if (!catalogDomains.has(domain)) {
      messages.push(`${prefix} references unknown domain: ${domain}`);
    }
  }
}

function requireAuthoringGuardrails(root: string, messages: string[]): void {
  requireDataFile(root, "authoring-guardrails.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const guardrail of listAuthoringGuardrails()) {
    const prefix = `authoring guardrail ${guardrail.id}`;
    if (ids.has(guardrail.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(guardrail.id);
    requireAuthoringDomains(prefix, guardrail.domains, domains, messages);
    if (guardrail.rules.length === 0) {
      messages.push(`${prefix} must list at least one rule`);
    }
    if (guardrail.requiredEvidence.length === 0) {
      messages.push(`${prefix} must list required evidence`);
    }
    if (!guardrail.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
  }
}

function requireAuthoringDiagnostics(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "authoring-diagnostics.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const diagnostic of listAuthoringDiagnostics()) {
    const prefix = `authoring diagnostic ${diagnostic.id}`;
    if (ids.has(diagnostic.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(diagnostic.id);
    requireAuthoringDomains(prefix, diagnostic.domains, domains, messages);
    if (diagnostic.severity !== "error" && diagnostic.severity !== "warning") {
      messages.push(`${prefix} must use severity error or warning`);
    }
    if (diagnostic.detectWhen.length === 0) {
      messages.push(`${prefix} must describe when to detect it`);
    }
    if (diagnostic.requiredChecks.length === 0) {
      messages.push(`${prefix} must list required checks`);
    }
    if (diagnostic.evidence.length === 0) {
      messages.push(`${prefix} must list evidence expectations`);
    }
    if (
      diagnostic.tools.cli.length === 0 &&
      diagnostic.tools.mcp.length === 0 &&
      diagnostic.tools.packageApis.length === 0
    ) {
      messages.push(`${prefix} must expose at least one CLI, MCP, or package API entrypoint`);
    }
    requirePublicEntrypoints(prefix, diagnostic.tools, publicEntrypoints, messages);
    if (diagnostic.failIf.length === 0) {
      messages.push(`${prefix} must list fail conditions`);
    }
    if (diagnostic.safeResponse.length === 0) {
      messages.push(`${prefix} must list safe responses`);
    }
    if (!diagnostic.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
  }
}

function requireAuthoringRecipes(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "authoring-recipes.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const finalCheckIds = new Set([
    ...listOutputRequirements().map((requirement) => requirement.id),
    ...listClaimPolicies().map((policy) => policy.id),
    ...listAuthoringGuardrails().map((guardrail) => guardrail.id),
  ]);
  const ids = new Set<string>();
  for (const recipe of listAuthoringRecipes()) {
    const prefix = `authoring recipe ${recipe.id}`;
    if (ids.has(recipe.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(recipe.id);
    requireAuthoringDomains(prefix, recipe.domains, domains, messages);
    if (recipe.when.length === 0) {
      messages.push(`${prefix} must describe when to use it`);
    }
    if (recipe.steps.length === 0) {
      messages.push(`${prefix} must list at least one step`);
    }
    if (recipe.finalChecks.length === 0) {
      messages.push(`${prefix} must list final checks`);
    }
    for (const finalCheck of recipe.finalChecks) {
      if (!finalCheckIds.has(finalCheck)) {
        messages.push(`${prefix} references unknown final check: ${finalCheck}`);
      }
    }
    if (!recipe.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
    const stepIds = new Set<string>();
    for (const [index, step] of recipe.steps.entries()) {
      const stepPrefix = `${prefix} step ${index + 1}`;
      if (stepIds.has(step.id)) {
        messages.push(`${stepPrefix} must not be duplicated`);
      }
      stepIds.add(step.id);
      if (!step.action) {
        messages.push(`${stepPrefix} must describe an action`);
      }
      if (step.evidence.length === 0) {
        messages.push(`${stepPrefix} must list evidence expectations`);
      }
      if (!step.stopIfMissing) {
        messages.push(`${stepPrefix} must describe what to do when evidence is missing`);
      }
      if (
        step.tools.cli.length === 0 &&
        step.tools.mcp.length === 0 &&
        step.tools.packageApis.length === 0
      ) {
        messages.push(`${stepPrefix} must expose at least one CLI, MCP, or package API entrypoint`);
      }
      requirePublicEntrypoints(stepPrefix, step.tools, publicEntrypoints, messages);
    }
  }
}

function requireAuthoringScenarios(root: string, messages: string[]): void {
  requireDataFile(root, "authoring-scenarios.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const recipeDomains = new Map(
    listAuthoringRecipes().map((recipe) => [recipe.id, recipe.domains] as const),
  );
  const intentDomains = new Map(
    listIntentLookups().map((intent) => [intent.id, intent.domains] as const),
  );
  const diagnosticDomains = new Map(
    listAuthoringDiagnostics().map((diagnostic) => [diagnostic.id, diagnostic.domains] as const),
  );
  const claimPolicyDomains = new Map(
    listClaimPolicies().map((policy) => [policy.id, policy.domains] as const),
  );
  const factSurfaceDomains = new Map(
    listFactSurfaces().map((surface) => [surface.id, surface.domains] as const),
  );
  const responsePatternDomains = new Map(
    listResponsePatterns().map((pattern) => [pattern.id, pattern.domains] as const),
  );
  const ids = new Set<string>();
  const referenced = {
    recipes: recipeDomains,
    intents: intentDomains,
    diagnostics: diagnosticDomains,
    claimPolicies: claimPolicyDomains,
    factSurfaces: factSurfaceDomains,
    responsePatterns: responsePatternDomains,
  };
  for (const scenario of listAuthoringScenarios()) {
    const prefix = `authoring scenario ${scenario.id}`;
    if (ids.has(scenario.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(scenario.id);
    if (scenario.domains.length === 0) {
      messages.push(`${prefix} must list at least one domain`);
    }
    for (const domain of scenario.domains) {
      if (!domains.has(domain)) {
        messages.push(`${prefix} references unknown domain: ${domain}`);
      }
    }
    if (!scenario.userPrompt) {
      messages.push(`${prefix} must include a representative user prompt`);
    }
    if (scenario.useWhen.length === 0) {
      messages.push(`${prefix} must describe when to use it`);
    }
    if (scenario.successCriteria.length === 0) {
      messages.push(`${prefix} must list success criteria`);
    }
    if (scenario.mustAvoid.length === 0) {
      messages.push(`${prefix} must list failure patterns to avoid`);
    }
    if (!scenario.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
    for (const [kind, expectedIds] of Object.entries(referenced)) {
      const actualIds = scenario.requiredLookups[kind as keyof typeof scenario.requiredLookups];
      if (actualIds.length === 0) {
        messages.push(`${prefix} must reference at least one ${kind} entry`);
      }
      for (const id of actualIds) {
        const referencedDomains = expectedIds.get(id);
        if (!referencedDomains) {
          messages.push(`${prefix} references unknown ${kind} entry: ${id}`);
          continue;
        }
        if (!referencedDomains.some((domain) => scenario.domains.includes(domain))) {
          messages.push(`${prefix} references ${kind} entry outside scenario domains: ${id}`);
        }
      }
    }
  }
}

function requireClaimPolicies(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "claim-policies.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const policy of listClaimPolicies()) {
    const prefix = `claim policy ${policy.id}`;
    if (ids.has(policy.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(policy.id);
    if (policy.domains.length === 0) {
      messages.push(`${prefix} must list at least one domain`);
    }
    for (const domain of policy.domains) {
      if (!domains.has(domain)) {
        messages.push(`${prefix} references unknown domain: ${domain}`);
      }
    }
    if (policy.requiredEvidence.length === 0) {
      messages.push(`${prefix} must list required evidence`);
    }
    if (policy.allowedWording.length === 0) {
      messages.push(`${prefix} must list allowed wording`);
    }
    if (policy.disallowedWording.length === 0) {
      messages.push(`${prefix} must list disallowed wording`);
    }
    if (!policy.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
    if (
      policy.tools.cli.length === 0 &&
      policy.tools.mcp.length === 0 &&
      policy.tools.packageApis.length === 0
    ) {
      messages.push(`${prefix} must expose at least one CLI, MCP, or package API entrypoint`);
    }
    requirePublicEntrypoints(prefix, policy.tools, publicEntrypoints, messages);
  }
}

function requireOutputRequirements(root: string, messages: string[]): void {
  requireDataFile(root, "output-requirements.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const requirement of listOutputRequirements()) {
    const prefix = `output requirement ${requirement.id}`;
    if (ids.has(requirement.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(requirement.id);
    if (requirement.domains.length === 0) {
      messages.push(`${prefix} must list at least one domain`);
    }
    for (const domain of requirement.domains) {
      if (!domains.has(domain)) {
        messages.push(`${prefix} references unknown domain: ${domain}`);
      }
    }
    if (requirement.mustInclude.length === 0) {
      messages.push(`${prefix} must list required output items`);
    }
    if (requirement.includeWhenRelevant.length === 0) {
      messages.push(`${prefix} must list conditional output items`);
    }
    if (requirement.mustNotInclude.length === 0) {
      messages.push(`${prefix} must list forbidden output items`);
    }
    if (!requirement.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
  }
}

function requireResponsePatterns(root: string, messages: string[]): void {
  requireDataFile(root, "response-patterns.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const pattern of listResponsePatterns()) {
    const prefix = `response pattern ${pattern.id}`;
    if (ids.has(pattern.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(pattern.id);
    if (pattern.domains.length === 0) {
      messages.push(`${prefix} must list at least one domain`);
    }
    for (const domain of pattern.domains) {
      if (!domains.has(domain)) {
        messages.push(`${prefix} references unknown domain: ${domain}`);
      }
    }
    if (pattern.useWhen.length === 0) {
      messages.push(`${prefix} must describe when to use it`);
    }
    if (pattern.requiredSections.length === 0) {
      messages.push(`${prefix} must list required answer sections`);
    }
    if (pattern.evidenceStatements.length === 0) {
      messages.push(`${prefix} must list evidence statements`);
    }
    if (pattern.gapStatements.length === 0) {
      messages.push(`${prefix} must list gap statements`);
    }
    if (pattern.mustAvoid.length === 0) {
      messages.push(`${prefix} must list avoided response patterns`);
    }
    if (!pattern.failureMode) {
      messages.push(`${prefix} must describe a failure mode`);
    }
  }
}

function requireIntentLookups(
  root: string,
  publicEntrypoints: PublicEntrypoints,
  messages: string[],
): void {
  requireDataFile(root, "intent-lookups.json", messages);
  const domains = new Set(listDomains().map((domain) => domain.id));
  const ids = new Set<string>();
  for (const intent of listIntentLookups()) {
    const prefix = `intent lookup ${intent.id}`;
    if (ids.has(intent.id)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    ids.add(intent.id);
    if (intent.domains.length === 0) {
      messages.push(`${prefix} must list at least one domain`);
    }
    for (const domain of intent.domains) {
      if (!domains.has(domain)) {
        messages.push(`${prefix} references unknown domain: ${domain}`);
      }
    }
    if (intent.when.length === 0) {
      messages.push(`${prefix} must describe when to use it`);
    }
    if (intent.lookups.length === 0) {
      messages.push(`${prefix} must list at least one lookup`);
    }
    for (const [index, lookup] of intent.lookups.entries()) {
      const lookupPrefix = `${prefix} lookup ${index + 1}`;
      if (lookup.evidence.length === 0) {
        messages.push(`${lookupPrefix} must list evidence expectations`);
      }
      if (!lookup.failureMode) {
        messages.push(`${lookupPrefix} must describe a failure mode`);
      }
      if (
        lookup.tools.cli.length === 0 &&
        lookup.tools.mcp.length === 0 &&
        lookup.tools.packageApis.length === 0
      ) {
        messages.push(
          `${lookupPrefix} must expose at least one CLI, MCP, or package API entrypoint`,
        );
      }
      requirePublicEntrypoints(lookupPrefix, lookup.tools, publicEntrypoints, messages);
    }
  }
}

function requireGeneratedHeader(root: string, path: string, messages: string[]): void {
  const absolutePath = join(root, path);
  requireFile(root, path, messages);
  if (existsSync(absolutePath) && !readFileSync(absolutePath, "utf8").includes(generatedHeader)) {
    messages.push(`missing generated header: ${path}`);
  }
}

function readYamlStringField(content: string, key: string): string | undefined {
  const match = content.match(new RegExp(`^\\s*${key}:\\s*"([^"]+)"\\s*$`, "m"));
  return match?.[1];
}

function requireSkillMetadata(root: string, skill: string, messages: string[]): void {
  const skillPath = `skills/${skill}/SKILL.md`;
  const skillAbsolutePath = join(root, skillPath);
  requireGeneratedHeader(root, skillPath, messages);

  if (existsSync(skillAbsolutePath)) {
    const content = readFileSync(skillAbsolutePath, "utf8");
    const frontmatter = content.match(/^---\n([\s\S]*?)\n---/);
    if (!frontmatter) {
      messages.push(`missing skill frontmatter: ${skillPath}`);
    } else {
      const frontmatterBody = frontmatter[1] ?? "";
      const keys = [...frontmatterBody.matchAll(/^([a-z_]+):/gm)].map((match) => match[1] ?? "");
      if (keys.join(",") !== "name,description") {
        messages.push(`skill frontmatter must contain only name and description: ${skillPath}`);
      }
      if (!frontmatterBody.includes(`name: ${skill}`)) {
        messages.push(`skill frontmatter name must match folder: ${skillPath}`);
      }
      if (!/^description: .+/m.test(frontmatterBody)) {
        messages.push(`missing skill description: ${skillPath}`);
      }
    }
  }

  const openaiYamlPath = `skills/${skill}/agents/openai.yaml`;
  const openaiYamlAbsolutePath = join(root, openaiYamlPath);
  requireFile(root, openaiYamlPath, messages);
  if (!existsSync(openaiYamlAbsolutePath)) {
    return;
  }

  const metadata = readFileSync(openaiYamlAbsolutePath, "utf8");
  const displayName = readYamlStringField(metadata, "display_name");
  const shortDescription = readYamlStringField(metadata, "short_description");
  const defaultPrompt = readYamlStringField(metadata, "default_prompt");
  if (!displayName) {
    messages.push(`missing display_name: ${openaiYamlPath}`);
  }
  if (!shortDescription) {
    messages.push(`missing short_description: ${openaiYamlPath}`);
  } else if (shortDescription.length < 25 || shortDescription.length > 64) {
    messages.push(`short_description must be 25-64 characters: ${openaiYamlPath}`);
  }
  if (!defaultPrompt) {
    messages.push(`missing default_prompt: ${openaiYamlPath}`);
  } else if (!defaultPrompt.includes(`$${skill}`)) {
    messages.push(`default_prompt must mention $${skill}: ${openaiYamlPath}`);
  }
}

function requireMirroredDataFile(root: string, path: string, messages: string[]): void {
  const sourcePath = join(root, path);
  const bundledPath = join(root, dataFilePath(path));
  requireFile(root, path, messages);
  requireDataFile(root, path, messages);
  if (
    existsSync(sourcePath) &&
    existsSync(bundledPath) &&
    readFileSync(sourcePath, "utf8") !== readFileSync(bundledPath, "utf8")
  ) {
    messages.push(`packaged data mirror differs from source: ${path}`);
  }
}

function requireSkillPayloadMirror(root: string, skill: string, messages: string[]): void {
  requireMirroredDataFile(root, `skills/${skill}/SKILL.md`, messages);
  requireMirroredDataFile(root, `skills/${skill}/agents/openai.yaml`, messages);
}

function materializeVersionDetails(root: string): number {
  let written = 0;
  for (const version of listVersions("java")) {
    writeFileSync(
      join(root, dataFilePath(`java/version-details/${version.id}.json`)),
      `${JSON.stringify(getVersionDetail("java", version.id), null, 2)}\n`,
    );
    written += 1;
  }
  return written;
}

function validationSampleContent(
  domain: "datapack" | "resourcepack",
  path: string,
  detail: ReturnType<typeof getVersionDetail>,
): string | unknown {
  if (path.endsWith("pack.mcmeta")) {
    return {
      pack: {
        pack_format: domain === "datapack" ? detail.packFormats.data : detail.packFormats.resource,
        description: "minecraft-skills validation sample",
      },
    };
  }
  if (path.endsWith(".json")) {
    return {};
  }
  return "";
}

function validationClassKey(
  version: string,
  domain: "datapack" | "resourcepack",
  path: string,
): string {
  const normalized = path.replaceAll("\\", "/");
  const parts = normalized.split("/");
  if (path.endsWith("pack.mcmeta")) {
    return `${version}\t${domain}\tpack.mcmeta`;
  }
  if (normalized === "data/.mcassetsroot" || normalized === "assets/.mcassetsroot") {
    return `${version}\t${domain}\t.mcassetsroot`;
  }
  if (domain === "datapack") {
    const nestedDataIndex =
      parts[0] === "data" && parts[2] === "datapacks"
        ? parts.findIndex((part, index) => index > 2 && part === "data")
        : -1;
    const datapackParts = nestedDataIndex === -1 ? parts : parts.slice(nestedDataIndex);
    const top = datapackParts[2] ?? "";
    const second = datapackParts[3] ?? "";
    const extension = path.includes(".") ? (path.split(".").at(-1) ?? "") : "";
    const kind =
      top === "tags"
        ? `tag/${second}`
        : top === "worldgen"
          ? `worldgen/${second}`
          : top === "functions" || top === "function"
            ? "function"
            : top === "structures" || top === "structure"
              ? "structure"
              : top;
    return `${version}\t${domain}\t${kind}\t${extension}`;
  }
  const top = parts[2] ?? "";
  const second = parts[3] ?? "";
  const extension = path.includes(".") ? (path.split(".").at(-1) ?? "") : "";
  const kind =
    top === "models"
      ? "model"
      : top === "items"
        ? "item-definition"
        : top === "textures"
          ? `texture/${second}`
          : top === "shaders"
            ? `shader/${second}`
            : top === "sounds"
              ? "sound-asset"
              : top;
  return `${version}\t${domain}\t${kind}\t${extension}`;
}

function requirePackContentValidationSamples(root: string, messages: string[]): void {
  let checked = 0;
  const failures: string[] = [];
  const validationCache = new Map<string, true>();
  for (const version of listVersions("java")) {
    const detail = getVersionDetail("java", version.id);
    for (const domain of ["datapack", "resourcepack"] as const) {
      const pathIndex = join(root, dataFilePath(`java/vanilla-paths/${version.id}.${domain}.txt`));
      const paths = readFileSync(pathIndex, "utf8").trim().split(/\r?\n/).filter(Boolean);
      for (const path of paths) {
        checked += 1;
        const cacheKey = validationClassKey(version.id, domain, path);
        if (validationCache.has(cacheKey)) {
          continue;
        }
        const result = validatePackFileContent({
          version: version.id,
          domain,
          path,
          content: validationSampleContent(domain, path, detail),
        });
        if (!result.valid) {
          failures.push(
            `${version.id} ${domain} ${path}: ${result.issues
              .map((issue) => `${issue.keyword ?? "unknown"} ${issue.message}`)
              .join("; ")}`,
          );
          if (failures.length >= 50) {
            break;
          }
        } else {
          validationCache.set(cacheKey, true);
        }
      }
      if (failures.length >= 50) {
        break;
      }
    }
    if (failures.length >= 50) {
      break;
    }
  }
  if (checked === 0) {
    messages.push("pack content validation must check at least one vanilla path");
  }
  if (failures.length > 0) {
    messages.push(
      `pack content validation must pass for every bundled vanilla path; checked ${checked} before failing:\n${failures.join(
        "\n",
      )}`,
    );
  }
}

export function validateRepository(): ValidationResult {
  const messages: string[] = [];
  const root = findRepositoryRoot();
  const catalog = getCatalog();
  const javaVersions = listVersions("java");
  const paper = getPaperPluginData();
  const publicEntrypoints = collectPublicEntrypoints(root);

  requireDataManifestIntegrity(root, messages);
  requireSourcePolicyIntegrity(root, messages);
  requireDocumentationIntegrity(root, messages);
  requireFactSurfaces(root, publicEntrypoints, messages);
  requireAuthoringChecklists(root, publicEntrypoints, messages);
  requireAuthoringGuardrails(root, messages);
  requireAuthoringDiagnostics(root, publicEntrypoints, messages);
  requireAuthoringRecipes(root, publicEntrypoints, messages);
  requireAuthoringScenarios(root, messages);
  requireClaimPolicies(root, publicEntrypoints, messages);
  requireOutputRequirements(root, messages);
  requireResponsePatterns(root, messages);
  requireIntentLookups(root, publicEntrypoints, messages);
  requirePackContentValidationSamples(root, messages);

  if (catalog.supportPolicy.javaPrimarySince !== "1.13") {
    messages.push("Java primary support must start at 1.13");
  }

  if (catalog.latest.java !== javaVersions[0]?.id) {
    messages.push("catalog latest Java version must match bundled Java version index");
  }

  for (const domain of listDomains()) {
    const skillEntry = catalog.skills.find((skill) => skill.name === domain.skill);
    if (!skillEntry) {
      messages.push(`missing catalog skill entry for domain: ${domain.id}`);
    } else {
      if (skillEntry.domain !== domain.id) {
        messages.push(`catalog skill domain mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.path !== `skills/${domain.skill}`) {
        messages.push(`catalog skill path mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.skillFile !== `skills/${domain.skill}/SKILL.md`) {
        messages.push(`catalog skill SKILL.md path mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.agentMetadata !== `skills/${domain.skill}/agents/openai.yaml`) {
        messages.push(`catalog skill agent metadata path mismatch: ${skillEntry.name}`);
      }
    }
    requireSkillMetadata(root, domain.skill, messages);
    requireSkillPayloadMirror(root, domain.skill, messages);
  }

  for (const reference of listReferences()) {
    requireGeneratedHeader(root, reference.path, messages);
    requireMirroredDataFile(root, reference.path, messages);
  }

  const latest = getVersionDetail("java", "latest");
  if (latest.coverage === "complete" && latest.packFormats.status !== "extracted") {
    messages.push("complete version coverage must include extracted pack formats");
  }

  for (const version of javaVersions) {
    const detail = getVersionDetail("java", version.id);
    const rawDetail = readJsonFile<ReturnType<typeof getVersionDetail>>(
      join(root, dataFilePath(`java/version-details/${version.id}.json`)),
    );
    const prefix = `java ${version.id}`;
    requireDataFile(root, `java/version-details/${version.id}.json`, messages);
    requireDataFile(root, `java/reports/${version.id}.json`, messages);
    requireDataFile(root, `java/command-paths/${version.id}.txt`, messages);
    requireDataFile(root, `java/registry-entries/${version.id}.tsv`, messages);
    requireDataFile(root, `java/vanilla-inventories/${version.id}.json`, messages);
    requireDataFile(root, `java/vanilla-paths/${version.id}.datapack.txt`, messages);
    requireDataFile(root, `java/vanilla-paths/${version.id}.resourcepack.txt`, messages);
    requireDataFile(root, `java/resourcepack-models/${version.id}.json`, messages);

    if (detail.coverage !== "version-json-and-jar") {
      messages.push(`${prefix} detail must have version-json-and-jar coverage`);
    }
    if (JSON.stringify(rawDetail.domains) !== JSON.stringify(detail.domains)) {
      messages.push(`${prefix} version detail must materialize derived domain coverage`);
    }
    if (
      detail.packFormats.status !== "extracted" ||
      detail.packFormats.data === null ||
      detail.packFormats.resource === null
    ) {
      messages.push(`${prefix} must have extracted data and resource pack formats`);
    }
    if (
      detail.domains.datapack.status !== "reports-extracted" ||
      detail.domains.datapack.unknowns.length > 0
    ) {
      messages.push(`${prefix} datapack coverage must include reports with no unknowns`);
    }
    if (
      detail.domains.resourcepack.status !== "models-extracted" ||
      detail.domains.resourcepack.unknowns.length > 0
    ) {
      messages.push(`${prefix} resourcepack coverage must include models with no unknowns`);
    }
  }

  for (const version of listPendingJavaReportVersions(root)) {
    messages.push(`java ${version} report summary or companion index needs repair`);
  }

  requireDataFile(root, `java/datapack-schema-surfaces/${catalog.latest.java}.json`, messages);
  try {
    getDatapackSchemaSurface("java", catalog.latest.java);
  } catch (error) {
    messages.push(
      `latest Java datapack schema surface must validate: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }

  for (const paperVersion of paper.versions) {
    const prefix = `paper ${paperVersion}`;
    const detail = getVersionDetail("java", paperVersion);
    const build = paper.versionBuilds.find(
      (candidate) => candidate.minecraftVersion === paperVersion,
    );
    if (!build) {
      messages.push(`${prefix} must have latest build metadata`);
    }
    if (detail.domains["paper-plugin"].status !== "api-reference-linked") {
      messages.push(`${prefix} must be linked from Java version details`);
    }
    const apiIndexPath = dataFilePath(`java/paper-api-indexes/${paperVersion}.json`);
    if (existsSync(join(root, apiIndexPath))) {
      if (
        !detail.domains["paper-plugin"].facts.includes(`paper_api_package_index=${paperVersion}`)
      ) {
        messages.push(`${prefix} must expose bundled Paper API package index fact`);
      }
      if (detail.domains["paper-plugin"].unknowns.length > 0) {
        messages.push(`${prefix} must not keep Paper API unknowns when package index is bundled`);
      }
    } else if (!detail.domains["paper-plugin"].unknowns.includes("server_api_changes")) {
      messages.push(`${prefix} must record server_api_changes when package index is unavailable`);
    }
  }

  requireDataFile(root, `java/paper-api-surfaces/${paper.latest.minecraftVersion}.json`, messages);
  try {
    getPaperApiSurface(paper.latest.minecraftVersion);
  } catch (error) {
    messages.push(
      `latest Paper API surface must validate: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }

  return {
    ok: messages.length === 0,
    messages,
  };
}

function printHelp(): void {
  console.log(`minecraft-skills-maintainer

Usage:
  minecraft-skills-maintainer validate
  minecraft-skills-maintainer audit-current-sources
  minecraft-skills-maintainer package-smoke [--keep-temp]
  minecraft-skills-maintainer write-data-manifest [--data-version <version>] [--base-url <url>]
  minecraft-skills-maintainer ingest-java-manifest --input <manifest.json> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-detail --version-json <version.json> [--version-json-url <url>] [--client-jar <client.jar>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-details [--skip-client-jars] [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer generate-java-reports --server-jar <server.jar> --work-dir <dir> --output-dir <dir> [--java-bin <java>]
  minecraft-skills-maintainer ingest-java-reports --version <version> --reports-dir <generated/reports> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-reports-all [--java-bin <java>] [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer audit-java-reports
  minecraft-skills-maintainer ingest-paper-project --project-json <project.json> [--java-latest <version>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-builds [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-api-indexes [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-api-surfaces [--version <paper-version>] [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer materialize-version-details
  minecraft-skills-maintainer ingest-vanilla-inventory --version <version> --client-jar <client.jar> --server-jar <server.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-vanilla-inventories [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-datapack-schema --version <version> --server-jar <server.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-datapack-schemas-all [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models --version <version> --client-jar <client.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models-all [--force] [--retrieved-at <iso>]

Commands:
  validate              Validate checked-in data, catalog, and generated skills.
  audit-current-sources Compare bundled latest Java/Paper data with Mojang and PaperMC APIs.
  package-smoke         Pack public packages, install them in a temp project, and smoke-test imports/bins.
  write-data-manifest   Regenerate downloadable heavy data manifest from checked-in surface files.
  ingest-java-manifest  Generate Java 1.13+ release index from Mojang version manifest.
  ingest-java-version-detail
                        Generate detail JSON from Mojang version JSON and optional client jar.
  ingest-java-version-details
                        Download and generate missing detail JSON for all indexed Java releases.
  generate-java-reports
                        Run Mojang data generator reports from a server jar.
  ingest-java-reports   Generate compact report summary, command paths, and registry entry index from server reports.
  ingest-java-reports-all
                        Download server jars and generate missing or incomplete reports and indexes.
  audit-java-reports    Report versions whose server report summaries or indexes need repair.
  ingest-paper-project
                        Generate Paper plugin support and event search data from PaperMC API JSON.
  ingest-paper-builds  Download latest build summaries for all bundled Paper-supported versions.
  ingest-paper-api-indexes
                        Download Paper Javadocs package indexes for supported versions.
  ingest-paper-api-surfaces
                        Download Paper Javadocs type/member search indexes.
  materialize-version-details
                        Write derived domain coverage facts into checked-in version detail JSON.
  ingest-vanilla-inventory
                        Generate compact inventory for vanilla client assets and server data.
  ingest-vanilla-inventories
                        Download and generate missing vanilla inventories for all indexed Java releases.
  ingest-datapack-schema
                        Generate observed vanilla datapack JSON field-shape surface from a server jar.
  ingest-datapack-schemas-all
                        Download and generate missing observed datapack JSON field-shape surfaces for all indexed Java releases.
  ingest-resourcepack-models
                        Generate compact resource pack model summary from a client jar.
  ingest-resourcepack-models-all
                        Download and generate missing resource pack model summaries for all indexed Java releases.`);
}

function readOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index === -1) {
    return undefined;
  }
  return args[index + 1];
}

function ingestJavaManifest(args: string[]): void {
  const input = readOption(args, "--input");
  if (!input) {
    throw new Error("ingest-java-manifest requires --input <manifest.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const manifest = JSON.parse(readFileSync(input, "utf8")) as unknown;
  const versionIndex = buildJavaVersionIndex(manifest, retrievedAt);
  const root = findRepositoryRoot();
  const output = join(root, "packages/data/data/java/versions.json");
  writeFileSync(output, `${JSON.stringify(versionIndex, null, 2)}\n`);
  console.log(`wrote ${versionIndex.versions.length} Java 1.13+ releases to ${output}`);
}

function ingestJavaVersionDetail(args: string[]): void {
  const versionJsonPath = readOption(args, "--version-json");
  if (!versionJsonPath) {
    throw new Error("ingest-java-version-detail requires --version-json <version.json>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  const versionJsonUrl = readOption(args, "--version-json-url");
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const options: {
    versionJsonPath: string;
    clientJarPath?: string;
    versionJsonUrl?: string;
    retrievedAt: string;
  } = {
    versionJsonPath,
    retrievedAt,
  };
  if (clientJarPath) {
    options.clientJarPath = clientJarPath;
  }
  if (versionJsonUrl) {
    options.versionJsonUrl = versionJsonUrl;
  }
  const detail = buildJavaVersionDetail(options);
  const root = findRepositoryRoot();
  const output = join(root, `packages/data/data/java/version-details/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(detail, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} detail to ${output}`);
}

async function ingestAllJavaVersionDetails(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestJavaVersionDetails({
    root,
    retrievedAt,
    includeClientJars: !args.includes("--skip-client-jars"),
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java version detail files`);
}

function ingestJavaReports(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-java-reports requires --version <version>");
  }
  const reportsDir = readOption(args, "--reports-dir");
  if (!reportsDir) {
    throw new Error("ingest-java-reports requires --reports-dir <generated/reports>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildJavaReportsSummary({
    version: detail.version,
    reportsDir,
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  writeJavaReportsSummary({
    root,
    version: detail.version,
    ...summary,
  });
  console.log(`wrote Java ${detail.version} reports summary, command paths, and registry entries`);
}

async function ingestAllJavaReports(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const written = await ingestJavaReportSummaries({
    root,
    retrievedAt: readOption(args, "--retrieved-at") ?? new Date().toISOString(),
    javaBin: readOption(args, "--java-bin") ?? "java",
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java report summaries and companion indexes`);
}

function generateReports(args: string[]): void {
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("generate-java-reports requires --server-jar <server.jar>");
  }
  const workDir = readOption(args, "--work-dir");
  if (!workDir) {
    throw new Error("generate-java-reports requires --work-dir <dir>");
  }
  const outputDir = readOption(args, "--output-dir");
  if (!outputDir) {
    throw new Error("generate-java-reports requires --output-dir <dir>");
  }
  generateJavaReports({
    javaBin: readOption(args, "--java-bin") ?? "java",
    serverJarPath,
    workDir,
    outputDir,
  });
  console.log(`wrote generated Java reports to ${outputDir}`);
}

function ingestPaperProject(args: string[]): void {
  const projectJsonPath = readOption(args, "--project-json");
  if (!projectJsonPath) {
    throw new Error("ingest-paper-project requires --project-json <project.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const latest = getVersionDetail("java", readOption(args, "--java-latest") ?? "latest");
  const paper = buildPaperPluginData({
    projectJson: JSON.parse(readFileSync(projectJsonPath, "utf8")) as unknown,
    javaLatest: latest.version,
    retrievedAt,
  });
  const output = join(root, "packages/data/data/java/paper.json");
  writeFileSync(output, `${JSON.stringify(paper, null, 2)}\n`);
  console.log(`wrote Paper plugin data to ${output}`);
}

async function ingestAllPaperBuilds(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperBuilds({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper version build summaries`);
}

async function ingestAllPaperApiIndexes(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperApiIndexes({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper API package index files`);
}

async function ingestAllPaperApiSurfaces(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const onlyVersion = readOption(args, "--version");
  const written = await ingestPaperApiSurfaces({
    root,
    retrievedAt,
    ...(onlyVersion ? { onlyVersion } : {}),
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper API surface files`);
}

function regenerateDataManifest(args: string[]): void {
  const root = findRepositoryRoot();
  const output = writeDataManifest(
    root,
    readOption(args, "--data-version"),
    readOption(args, "--base-url"),
  );
  console.log(`wrote data manifest to ${output}`);
}

function readDownloadUrl(downloads: Record<string, unknown>, key: string): string {
  const download = downloads[key];
  if (download && typeof download === "object" && "url" in download) {
    const url = (download as { url: unknown }).url;
    if (typeof url === "string") {
      return url;
    }
  }
  throw new Error(`Version detail does not include downloads.${key}.url`);
}

function writeVanillaPathIndex(root: string, version: string, paths: VanillaPathIndex): void {
  const outputRoot = join(root, "packages/data/data/java/vanilla-paths");
  mkdirSync(outputRoot, { recursive: true });
  writeFileSync(
    join(outputRoot, `${version}.resourcepack.txt`),
    `${paths.resourcepack.join("\n")}\n`,
  );
  writeFileSync(join(outputRoot, `${version}.datapack.txt`), `${paths.datapack.join("\n")}\n`);
}

function ingestVanillaInventory(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-vanilla-inventory requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-vanilla-inventory requires --client-jar <client.jar>");
  }
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("ingest-vanilla-inventory requires --server-jar <server.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const { inventory, paths } = buildVanillaData({
    version: detail.version,
    clientJarPath,
    serverJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  const output = join(root, `packages/data/data/java/vanilla-inventories/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(inventory, null, 2)}\n`);
  writeVanillaPathIndex(root, detail.version, paths);
  console.log(`wrote Java ${detail.version} vanilla inventory to ${output}`);
}

function ingestDatapackSchema(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-datapack-schema requires --version <version>");
  }
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("ingest-datapack-schema requires --server-jar <server.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const surface = buildObservedDatapackSchemaSurface({
    version: detail.version,
    serverJarPath,
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  const output = writeObservedDatapackSchemaSurface({ root, surface });
  console.log(`wrote Java ${detail.version} observed datapack schema surface to ${output}`);
}

async function ingestAllDatapackSchemas(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestDatapackSchemaSurfaces({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} datapack schema surface files`);
}

async function ingestAllVanillaInventories(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestVanillaInventories({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java vanilla inventory files`);
}

function ingestResourcepackModels(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-resourcepack-models requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-resourcepack-models requires --client-jar <client.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildResourcepackModelSummary({
    version: detail.version,
    clientJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    retrievedAt,
  });
  const outputRoot = join(root, "packages/data/data/java/resourcepack-models");
  mkdirSync(outputRoot, { recursive: true });
  const output = join(outputRoot, `${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(summary, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} resourcepack model summary to ${output}`);
}

async function ingestAllResourcepackModels(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestResourcepackModelSummaries({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java resourcepack model summary files`);
}

export async function runMaintainerCli(argv: string[]): Promise<number> {
  const [command] = argv;
  if (!command || command === "help" || command === "--help" || command === "-h") {
    printHelp();
    return 0;
  }

  try {
    if (command === "audit-current-sources") {
      const result = await auditCurrentSources();
      console.log(JSON.stringify(result, null, 2));
      return result.ok ? 0 : 1;
    }

    if (command === "package-smoke") {
      const result = runPackageSmoke({
        root: findRepositoryRoot(),
        keepTemp: argv.includes("--keep-temp"),
      });
      console.log(JSON.stringify(result, null, 2));
      return 0;
    }

    if (command === "write-data-manifest") {
      regenerateDataManifest(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-manifest") {
      ingestJavaManifest(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-detail") {
      ingestJavaVersionDetail(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-details") {
      await ingestAllJavaVersionDetails(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-reports") {
      ingestJavaReports(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-reports-all") {
      await ingestAllJavaReports(argv.slice(1));
      return 0;
    }

    if (command === "audit-java-reports") {
      const pendingVersions = listPendingJavaReportVersions(findRepositoryRoot());
      console.log(JSON.stringify({ ok: pendingVersions.length === 0, pendingVersions }, null, 2));
      return pendingVersions.length === 0 ? 0 : 1;
    }

    if (command === "generate-java-reports") {
      generateReports(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-project") {
      ingestPaperProject(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-builds") {
      await ingestAllPaperBuilds(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-api-indexes") {
      await ingestAllPaperApiIndexes(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-api-surfaces") {
      await ingestAllPaperApiSurfaces(argv.slice(1));
      return 0;
    }

    if (command === "materialize-version-details") {
      const root = findRepositoryRoot();
      const written = materializeVersionDetails(root);
      console.log(`wrote ${written} Java version detail files`);
      return 0;
    }

    if (command === "ingest-vanilla-inventory") {
      ingestVanillaInventory(argv.slice(1));
      return 0;
    }

    if (command === "ingest-vanilla-inventories") {
      await ingestAllVanillaInventories(argv.slice(1));
      return 0;
    }

    if (command === "ingest-datapack-schema") {
      ingestDatapackSchema(argv.slice(1));
      return 0;
    }

    if (command === "ingest-datapack-schemas-all") {
      await ingestAllDatapackSchemas(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models") {
      ingestResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models-all") {
      await ingestAllResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command !== "validate") {
      throw new Error(`Unknown command: ${command}`);
    }

    const result = validateRepository();
    if (!result.ok) {
      for (const message of result.messages) {
        console.error(message);
      }
      return 1;
    }
    console.log("minecraft-skills repository validation passed");
    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (isDirectRun(import.meta.url)) {
  process.exitCode = await runMaintainerCli(process.argv.slice(2));
}
