#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  getCatalog,
  getVersionDetail,
  listDomains,
  listReferences,
} from "@minecraft-skills/catalog";
import { buildJavaVersionIndex } from "./javaManifest.js";
import {
  buildJavaReportsSummary,
  generateJavaReports,
  writeJavaReportsSummary,
} from "./javaReports.js";
import { buildJavaVersionDetail } from "./javaVersionDetail.js";
import { ingestJavaVersionDetails } from "./javaVersionDetails.js";
import { ingestPaperApiIndexes } from "./paperApiIndexes.js";
import { ingestPaperBuilds } from "./paperBuilds.js";
import { buildPaperPluginData } from "./paperProject.js";
import { ingestResourcepackModelSummaries } from "./resourcepackModelSummaries.js";
import { buildResourcepackModelSummary } from "./resourcepackModels.js";
import { ingestVanillaInventories } from "./vanillaInventories.js";
import { buildVanillaData, type VanillaPathIndex } from "./vanillaInventory.js";

type ValidationResult = {
  ok: boolean;
  messages: string[];
};

const generatedHeader = "<!-- generated by @minecraft-skills/maintainer; do not edit directly -->";

function findRepositoryRoot(start = process.cwd()): string {
  let current = start;
  while (true) {
    if (existsSync(join(current, "pnpm-workspace.yaml"))) {
      return current;
    }
    const parent = dirname(current);
    if (parent === current) {
      throw new Error("Could not find repository root from current working directory");
    }
    current = parent;
  }
}

function requireFile(root: string, path: string, messages: string[]): void {
  if (!existsSync(join(root, path))) {
    messages.push(`missing file: ${path}`);
  }
}

function requireGeneratedHeader(root: string, path: string, messages: string[]): void {
  const absolutePath = join(root, path);
  requireFile(root, path, messages);
  if (existsSync(absolutePath) && !readFileSync(absolutePath, "utf8").includes(generatedHeader)) {
    messages.push(`missing generated header: ${path}`);
  }
}

export function validateRepository(): ValidationResult {
  const messages: string[] = [];
  const root = findRepositoryRoot();
  const catalog = getCatalog();

  if (catalog.supportPolicy.javaPrimarySince !== "1.13") {
    messages.push("Java primary support must start at 1.13");
  }

  for (const domain of listDomains()) {
    requireGeneratedHeader(root, `skills/${domain.skill}/SKILL.md`, messages);
  }

  for (const reference of listReferences()) {
    requireGeneratedHeader(root, reference.path, messages);
  }

  const latest = getVersionDetail("java", "latest");
  if (latest.coverage === "complete" && latest.packFormats.status !== "extracted") {
    messages.push("complete version coverage must include extracted pack formats");
  }

  return {
    ok: messages.length === 0,
    messages,
  };
}

function printHelp(): void {
  console.log(`minecraft-skills-maintainer

Usage:
  minecraft-skills-maintainer validate
  minecraft-skills-maintainer ingest-java-manifest --input <manifest.json> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-detail --version-json <version.json> [--version-json-url <url>] [--client-jar <client.jar>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-details [--skip-client-jars] [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer generate-java-reports --server-jar <server.jar> --work-dir <dir> --output-dir <dir> [--java-bin <java>]
  minecraft-skills-maintainer ingest-java-reports --version <version> --reports-dir <generated/reports> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-project --project-json <project.json> --latest-builds-json <builds.json> [--java-latest <version>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-builds [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-api-indexes [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-vanilla-inventory --version <version> --client-jar <client.jar> --server-jar <server.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-vanilla-inventories [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models --version <version> --client-jar <client.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models-all [--force] [--retrieved-at <iso>]

Commands:
  validate              Validate checked-in data, catalog, and generated skills.
  ingest-java-manifest  Generate Java 1.13+ release index from Mojang version manifest.
  ingest-java-version-detail
                        Generate detail JSON from Mojang version JSON and optional client jar.
  ingest-java-version-details
                        Download and generate missing detail JSON for all indexed Java releases.
  generate-java-reports
                        Run Mojang data generator reports from a server jar.
  ingest-java-reports   Generate compact report summary and command path index from server reports.
  ingest-paper-project
                        Generate Paper plugin support and event search data from PaperMC API JSON.
  ingest-paper-builds  Download latest build summaries for all bundled Paper-supported versions.
  ingest-paper-api-indexes
                        Download Paper Javadocs package indexes for supported versions.
  ingest-vanilla-inventory
                        Generate compact inventory for vanilla client assets and server data.
  ingest-vanilla-inventories
                        Download and generate missing vanilla inventories for all indexed Java releases.
  ingest-resourcepack-models
                        Generate compact resource pack model summary from a client jar.
  ingest-resourcepack-models-all
                        Download and generate missing resource pack model summaries for all indexed Java releases.`);
}

function readOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index === -1) {
    return undefined;
  }
  return args[index + 1];
}

function ingestJavaManifest(args: string[]): void {
  const input = readOption(args, "--input");
  if (!input) {
    throw new Error("ingest-java-manifest requires --input <manifest.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const manifest = JSON.parse(readFileSync(input, "utf8")) as unknown;
  const versionIndex = buildJavaVersionIndex(manifest, retrievedAt);
  const root = findRepositoryRoot();
  const output = join(root, "packages/data/data/java/versions.json");
  writeFileSync(output, `${JSON.stringify(versionIndex, null, 2)}\n`);
  console.log(`wrote ${versionIndex.versions.length} Java 1.13+ releases to ${output}`);
}

function ingestJavaVersionDetail(args: string[]): void {
  const versionJsonPath = readOption(args, "--version-json");
  if (!versionJsonPath) {
    throw new Error("ingest-java-version-detail requires --version-json <version.json>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  const versionJsonUrl = readOption(args, "--version-json-url");
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const options: {
    versionJsonPath: string;
    clientJarPath?: string;
    versionJsonUrl?: string;
    retrievedAt: string;
  } = {
    versionJsonPath,
    retrievedAt,
  };
  if (clientJarPath) {
    options.clientJarPath = clientJarPath;
  }
  if (versionJsonUrl) {
    options.versionJsonUrl = versionJsonUrl;
  }
  const detail = buildJavaVersionDetail(options);
  const root = findRepositoryRoot();
  const output = join(root, `packages/data/data/java/version-details/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(detail, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} detail to ${output}`);
}

async function ingestAllJavaVersionDetails(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestJavaVersionDetails({
    root,
    retrievedAt,
    includeClientJars: !args.includes("--skip-client-jars"),
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java version detail files`);
}

function ingestJavaReports(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-java-reports requires --version <version>");
  }
  const reportsDir = readOption(args, "--reports-dir");
  if (!reportsDir) {
    throw new Error("ingest-java-reports requires --reports-dir <generated/reports>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildJavaReportsSummary({
    version: detail.version,
    reportsDir,
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  writeJavaReportsSummary({
    root,
    version: detail.version,
    ...summary,
  });
  console.log(`wrote Java ${detail.version} reports summary and command paths`);
}

function generateReports(args: string[]): void {
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("generate-java-reports requires --server-jar <server.jar>");
  }
  const workDir = readOption(args, "--work-dir");
  if (!workDir) {
    throw new Error("generate-java-reports requires --work-dir <dir>");
  }
  const outputDir = readOption(args, "--output-dir");
  if (!outputDir) {
    throw new Error("generate-java-reports requires --output-dir <dir>");
  }
  generateJavaReports({
    javaBin: readOption(args, "--java-bin") ?? "java",
    serverJarPath,
    workDir,
    outputDir,
  });
  console.log(`wrote generated Java reports to ${outputDir}`);
}

function ingestPaperProject(args: string[]): void {
  const projectJsonPath = readOption(args, "--project-json");
  if (!projectJsonPath) {
    throw new Error("ingest-paper-project requires --project-json <project.json>");
  }
  const latestBuildsJsonPath = readOption(args, "--latest-builds-json");
  if (!latestBuildsJsonPath) {
    throw new Error("ingest-paper-project requires --latest-builds-json <builds.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const latest = getVersionDetail("java", readOption(args, "--java-latest") ?? "latest");
  const paper = buildPaperPluginData({
    projectJson: JSON.parse(readFileSync(projectJsonPath, "utf8")) as unknown,
    latestBuildsJson: JSON.parse(readFileSync(latestBuildsJsonPath, "utf8")) as unknown,
    javaLatest: latest.version,
    retrievedAt,
  });
  const output = join(root, "packages/data/data/java/paper.json");
  writeFileSync(output, `${JSON.stringify(paper, null, 2)}\n`);
  console.log(`wrote Paper plugin data to ${output}`);
}

async function ingestAllPaperBuilds(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperBuilds({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper version build summaries`);
}

async function ingestAllPaperApiIndexes(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperApiIndexes({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper API package index files`);
}

function readDownloadUrl(downloads: Record<string, unknown>, key: string): string {
  const download = downloads[key];
  if (download && typeof download === "object" && "url" in download) {
    const url = (download as { url: unknown }).url;
    if (typeof url === "string") {
      return url;
    }
  }
  throw new Error(`Version detail does not include downloads.${key}.url`);
}

function writeVanillaPathIndex(root: string, version: string, paths: VanillaPathIndex): void {
  const outputRoot = join(root, "packages/data/data/java/vanilla-paths");
  mkdirSync(outputRoot, { recursive: true });
  writeFileSync(
    join(outputRoot, `${version}.resourcepack.txt`),
    `${paths.resourcepack.join("\n")}\n`,
  );
  writeFileSync(join(outputRoot, `${version}.datapack.txt`), `${paths.datapack.join("\n")}\n`);
}

function ingestVanillaInventory(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-vanilla-inventory requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-vanilla-inventory requires --client-jar <client.jar>");
  }
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("ingest-vanilla-inventory requires --server-jar <server.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const { inventory, paths } = buildVanillaData({
    version: detail.version,
    clientJarPath,
    serverJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  const output = join(root, `packages/data/data/java/vanilla-inventories/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(inventory, null, 2)}\n`);
  writeVanillaPathIndex(root, detail.version, paths);
  console.log(`wrote Java ${detail.version} vanilla inventory to ${output}`);
}

async function ingestAllVanillaInventories(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestVanillaInventories({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java vanilla inventory files`);
}

function ingestResourcepackModels(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-resourcepack-models requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-resourcepack-models requires --client-jar <client.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildResourcepackModelSummary({
    version: detail.version,
    clientJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    retrievedAt,
  });
  const outputRoot = join(root, "packages/data/data/java/resourcepack-models");
  mkdirSync(outputRoot, { recursive: true });
  const output = join(outputRoot, `${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(summary, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} resourcepack model summary to ${output}`);
}

async function ingestAllResourcepackModels(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestResourcepackModelSummaries({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java resourcepack model summary files`);
}

export async function runMaintainerCli(argv: string[]): Promise<number> {
  const [command] = argv;
  if (!command || command === "help" || command === "--help" || command === "-h") {
    printHelp();
    return 0;
  }

  try {
    if (command === "ingest-java-manifest") {
      ingestJavaManifest(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-detail") {
      ingestJavaVersionDetail(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-details") {
      await ingestAllJavaVersionDetails(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-reports") {
      ingestJavaReports(argv.slice(1));
      return 0;
    }

    if (command === "generate-java-reports") {
      generateReports(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-project") {
      ingestPaperProject(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-builds") {
      await ingestAllPaperBuilds(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-api-indexes") {
      await ingestAllPaperApiIndexes(argv.slice(1));
      return 0;
    }

    if (command === "ingest-vanilla-inventory") {
      ingestVanillaInventory(argv.slice(1));
      return 0;
    }

    if (command === "ingest-vanilla-inventories") {
      await ingestAllVanillaInventories(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models") {
      ingestResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models-all") {
      await ingestAllResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command !== "validate") {
      throw new Error(`Unknown command: ${command}`);
    }

    const result = validateRepository();
    if (!result.ok) {
      for (const message of result.messages) {
        console.error(message);
      }
      return 1;
    }
    console.log("minecraft-skills repository validation passed");
    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exitCode = await runMaintainerCli(process.argv.slice(2));
}
