#!/usr/bin/env node
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  getCatalog,
  getDataManifest,
  getDatapackSchemaSurface,
  getPaperApiSurface,
  getPaperPluginData,
  getVersionDetail,
  listDomains,
  listReferences,
  listVersions,
} from "@minecraft-skills/catalog";
import { auditCurrentSources } from "./currentSources.js";
import {
  buildObservedDatapackSchemaSurface,
  writeObservedDatapackSchemaSurface,
} from "./datapackSchemaSurfaces.js";
import { buildJavaVersionIndex } from "./javaManifest.js";
import {
  buildJavaReportsSummary,
  generateJavaReports,
  writeJavaReportsSummary,
} from "./javaReports.js";
import { buildJavaVersionDetail } from "./javaVersionDetail.js";
import { ingestJavaVersionDetails } from "./javaVersionDetails.js";
import { runPackageSmoke } from "./packageSmoke.js";
import { ingestPaperApiIndexes } from "./paperApiIndexes.js";
import { ingestPaperApiSurfaces } from "./paperApiSurfaces.js";
import { ingestPaperBuilds } from "./paperBuilds.js";
import { buildPaperPluginData } from "./paperProject.js";
import { ingestResourcepackModelSummaries } from "./resourcepackModelSummaries.js";
import { buildResourcepackModelSummary } from "./resourcepackModels.js";
import { ingestVanillaInventories } from "./vanillaInventories.js";
import { buildVanillaData, type VanillaPathIndex } from "./vanillaInventory.js";

type ValidationResult = {
  ok: boolean;
  messages: string[];
};

const generatedHeader = "<!-- generated by @minecraft-skills/maintainer; do not edit directly -->";

function isDirectRun(metaUrl: string): boolean {
  return process.argv[1]
    ? realpathSync(fileURLToPath(metaUrl)) === realpathSync(process.argv[1])
    : false;
}

function findRepositoryRoot(start = process.cwd()): string {
  let current = start;
  while (true) {
    if (existsSync(join(current, "pnpm-workspace.yaml"))) {
      return current;
    }
    const parent = dirname(current);
    if (parent === current) {
      throw new Error("Could not find repository root from current working directory");
    }
    current = parent;
  }
}

function requireFile(root: string, path: string, messages: string[]): void {
  if (!existsSync(join(root, path))) {
    messages.push(`missing file: ${path}`);
  }
}

function dataFilePath(path: string): string {
  return `packages/data/data/${path}`;
}

function requireDataFile(root: string, path: string, messages: string[]): void {
  requireFile(root, dataFilePath(path), messages);
}

function readJsonFile<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

function isSafeRelativePath(path: string): boolean {
  return path.length > 0 && !path.includes("\0") && !path.split(/[\\/]/).includes("..");
}

function requireDataManifestIntegrity(root: string, messages: string[]): void {
  requireDataFile(root, "data-manifest.json", messages);
  const manifestPath = join(root, dataFilePath("data-manifest.json"));
  if (!existsSync(manifestPath)) {
    return;
  }

  const manifest = getDataManifest();
  if (manifest.schemaVersion !== 1) {
    messages.push("data manifest schemaVersion must be 1");
  }
  if (manifest.cache.environmentVariable !== "MINECRAFT_SKILLS_CACHE_DIR") {
    messages.push("data manifest cache environment variable must be MINECRAFT_SKILLS_CACHE_DIR");
  }

  const seenPaths = new Set<string>();
  for (const entry of manifest.downloadable) {
    const prefix = `data manifest entry ${entry.path}`;
    if (!isSafeRelativePath(entry.path)) {
      messages.push(`${prefix} must use a safe relative path`);
      continue;
    }
    if (seenPaths.has(entry.path)) {
      messages.push(`${prefix} must not be duplicated`);
    }
    seenPaths.add(entry.path);

    if (entry.kind === "datapack-schema-surface") {
      if (entry.edition !== "java" || !entry.version) {
        messages.push(`${prefix} datapack schema surface must identify Java version`);
      } else if (entry.path !== `java/datapack-schema-surfaces/${entry.version}.json`) {
        messages.push(`${prefix} datapack schema surface path must match version`);
      }
    } else if (entry.kind === "paper-api-surface") {
      if (entry.edition !== "java" || !entry.version) {
        messages.push(`${prefix} Paper API surface must identify Java version`);
      } else if (entry.path !== `java/paper-api-surfaces/${entry.version}.json`) {
        messages.push(`${prefix} Paper API surface path must match version`);
      }
    } else {
      messages.push(`${prefix} has unsupported downloadable kind: ${entry.kind}`);
    }

    try {
      new URL(entry.url);
    } catch {
      messages.push(`${prefix} must include a valid URL`);
    }

    const absolutePath = join(root, dataFilePath(entry.path));
    requireDataFile(root, entry.path, messages);
    if (!existsSync(absolutePath)) {
      continue;
    }
    const actualSize = statSync(absolutePath).size;
    if (actualSize !== entry.size) {
      messages.push(
        `${prefix} size must match checked-in file: expected ${entry.size}, got ${actualSize}`,
      );
    }
    const actualSha256 = sha256File(absolutePath);
    if (actualSha256 !== entry.sha256) {
      messages.push(
        `${prefix} sha256 must match checked-in file: expected ${entry.sha256}, got ${actualSha256}`,
      );
    }
  }
}

function requireGeneratedHeader(root: string, path: string, messages: string[]): void {
  const absolutePath = join(root, path);
  requireFile(root, path, messages);
  if (existsSync(absolutePath) && !readFileSync(absolutePath, "utf8").includes(generatedHeader)) {
    messages.push(`missing generated header: ${path}`);
  }
}

function readYamlStringField(content: string, key: string): string | undefined {
  const match = content.match(new RegExp(`^\\s*${key}:\\s*"([^"]+)"\\s*$`, "m"));
  return match?.[1];
}

function requireSkillMetadata(root: string, skill: string, messages: string[]): void {
  const skillPath = `skills/${skill}/SKILL.md`;
  const skillAbsolutePath = join(root, skillPath);
  requireGeneratedHeader(root, skillPath, messages);

  if (existsSync(skillAbsolutePath)) {
    const content = readFileSync(skillAbsolutePath, "utf8");
    const frontmatter = content.match(/^---\n([\s\S]*?)\n---/);
    if (!frontmatter) {
      messages.push(`missing skill frontmatter: ${skillPath}`);
    } else {
      const frontmatterBody = frontmatter[1] ?? "";
      const keys = [...frontmatterBody.matchAll(/^([a-z_]+):/gm)].map((match) => match[1] ?? "");
      if (keys.join(",") !== "name,description") {
        messages.push(`skill frontmatter must contain only name and description: ${skillPath}`);
      }
      if (!frontmatterBody.includes(`name: ${skill}`)) {
        messages.push(`skill frontmatter name must match folder: ${skillPath}`);
      }
      if (!/^description: .+/m.test(frontmatterBody)) {
        messages.push(`missing skill description: ${skillPath}`);
      }
    }
  }

  const openaiYamlPath = `skills/${skill}/agents/openai.yaml`;
  const openaiYamlAbsolutePath = join(root, openaiYamlPath);
  requireFile(root, openaiYamlPath, messages);
  if (!existsSync(openaiYamlAbsolutePath)) {
    return;
  }

  const metadata = readFileSync(openaiYamlAbsolutePath, "utf8");
  const displayName = readYamlStringField(metadata, "display_name");
  const shortDescription = readYamlStringField(metadata, "short_description");
  const defaultPrompt = readYamlStringField(metadata, "default_prompt");
  if (!displayName) {
    messages.push(`missing display_name: ${openaiYamlPath}`);
  }
  if (!shortDescription) {
    messages.push(`missing short_description: ${openaiYamlPath}`);
  } else if (shortDescription.length < 25 || shortDescription.length > 64) {
    messages.push(`short_description must be 25-64 characters: ${openaiYamlPath}`);
  }
  if (!defaultPrompt) {
    messages.push(`missing default_prompt: ${openaiYamlPath}`);
  } else if (!defaultPrompt.includes(`$${skill}`)) {
    messages.push(`default_prompt must mention $${skill}: ${openaiYamlPath}`);
  }
}

function requireMirroredDataFile(root: string, path: string, messages: string[]): void {
  const sourcePath = join(root, path);
  const bundledPath = join(root, dataFilePath(path));
  requireFile(root, path, messages);
  requireDataFile(root, path, messages);
  if (
    existsSync(sourcePath) &&
    existsSync(bundledPath) &&
    readFileSync(sourcePath, "utf8") !== readFileSync(bundledPath, "utf8")
  ) {
    messages.push(`packaged data mirror differs from source: ${path}`);
  }
}

function requireSkillPayloadMirror(root: string, skill: string, messages: string[]): void {
  requireMirroredDataFile(root, `skills/${skill}/SKILL.md`, messages);
  requireMirroredDataFile(root, `skills/${skill}/agents/openai.yaml`, messages);
}

function materializeVersionDetails(root: string): number {
  let written = 0;
  for (const version of listVersions("java")) {
    writeFileSync(
      join(root, dataFilePath(`java/version-details/${version.id}.json`)),
      `${JSON.stringify(getVersionDetail("java", version.id), null, 2)}\n`,
    );
    written += 1;
  }
  return written;
}

export function validateRepository(): ValidationResult {
  const messages: string[] = [];
  const root = findRepositoryRoot();
  const catalog = getCatalog();
  const javaVersions = listVersions("java");
  const paper = getPaperPluginData();

  requireDataManifestIntegrity(root, messages);

  if (catalog.supportPolicy.javaPrimarySince !== "1.13") {
    messages.push("Java primary support must start at 1.13");
  }

  if (catalog.latest.java !== javaVersions[0]?.id) {
    messages.push("catalog latest Java version must match bundled Java version index");
  }

  for (const domain of listDomains()) {
    const skillEntry = catalog.skills.find((skill) => skill.name === domain.skill);
    if (!skillEntry) {
      messages.push(`missing catalog skill entry for domain: ${domain.id}`);
    } else {
      if (skillEntry.domain !== domain.id) {
        messages.push(`catalog skill domain mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.path !== `skills/${domain.skill}`) {
        messages.push(`catalog skill path mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.skillFile !== `skills/${domain.skill}/SKILL.md`) {
        messages.push(`catalog skill SKILL.md path mismatch: ${skillEntry.name}`);
      }
      if (skillEntry.agentMetadata !== `skills/${domain.skill}/agents/openai.yaml`) {
        messages.push(`catalog skill agent metadata path mismatch: ${skillEntry.name}`);
      }
    }
    requireSkillMetadata(root, domain.skill, messages);
    requireSkillPayloadMirror(root, domain.skill, messages);
  }

  for (const reference of listReferences()) {
    requireGeneratedHeader(root, reference.path, messages);
    requireMirroredDataFile(root, reference.path, messages);
  }

  const latest = getVersionDetail("java", "latest");
  if (latest.coverage === "complete" && latest.packFormats.status !== "extracted") {
    messages.push("complete version coverage must include extracted pack formats");
  }

  for (const version of javaVersions) {
    const detail = getVersionDetail("java", version.id);
    const rawDetail = readJsonFile<ReturnType<typeof getVersionDetail>>(
      join(root, dataFilePath(`java/version-details/${version.id}.json`)),
    );
    const prefix = `java ${version.id}`;
    requireDataFile(root, `java/version-details/${version.id}.json`, messages);
    requireDataFile(root, `java/reports/${version.id}.json`, messages);
    requireDataFile(root, `java/command-paths/${version.id}.txt`, messages);
    requireDataFile(root, `java/vanilla-inventories/${version.id}.json`, messages);
    requireDataFile(root, `java/vanilla-paths/${version.id}.datapack.txt`, messages);
    requireDataFile(root, `java/vanilla-paths/${version.id}.resourcepack.txt`, messages);
    requireDataFile(root, `java/resourcepack-models/${version.id}.json`, messages);

    if (detail.coverage !== "version-json-and-jar") {
      messages.push(`${prefix} detail must have version-json-and-jar coverage`);
    }
    if (JSON.stringify(rawDetail.domains) !== JSON.stringify(detail.domains)) {
      messages.push(`${prefix} version detail must materialize derived domain coverage`);
    }
    if (
      detail.packFormats.status !== "extracted" ||
      detail.packFormats.data === null ||
      detail.packFormats.resource === null
    ) {
      messages.push(`${prefix} must have extracted data and resource pack formats`);
    }
    if (
      detail.domains.datapack.status !== "reports-extracted" ||
      detail.domains.datapack.unknowns.length > 0
    ) {
      messages.push(`${prefix} datapack coverage must include reports with no unknowns`);
    }
    if (
      detail.domains.resourcepack.status !== "models-extracted" ||
      detail.domains.resourcepack.unknowns.length > 0
    ) {
      messages.push(`${prefix} resourcepack coverage must include models with no unknowns`);
    }
  }

  requireDataFile(root, `java/datapack-schema-surfaces/${catalog.latest.java}.json`, messages);
  try {
    getDatapackSchemaSurface("java", catalog.latest.java);
  } catch (error) {
    messages.push(
      `latest Java datapack schema surface must validate: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }

  for (const paperVersion of paper.versions) {
    const prefix = `paper ${paperVersion}`;
    const detail = getVersionDetail("java", paperVersion);
    const build = paper.versionBuilds.find(
      (candidate) => candidate.minecraftVersion === paperVersion,
    );
    if (!build) {
      messages.push(`${prefix} must have latest build metadata`);
    }
    if (detail.domains["paper-plugin"].status !== "api-reference-linked") {
      messages.push(`${prefix} must be linked from Java version details`);
    }
    const apiIndexPath = dataFilePath(`java/paper-api-indexes/${paperVersion}.json`);
    if (existsSync(join(root, apiIndexPath))) {
      if (
        !detail.domains["paper-plugin"].facts.includes(`paper_api_package_index=${paperVersion}`)
      ) {
        messages.push(`${prefix} must expose bundled Paper API package index fact`);
      }
      if (detail.domains["paper-plugin"].unknowns.length > 0) {
        messages.push(`${prefix} must not keep Paper API unknowns when package index is bundled`);
      }
    } else if (!detail.domains["paper-plugin"].unknowns.includes("server_api_changes")) {
      messages.push(`${prefix} must record server_api_changes when package index is unavailable`);
    }
  }

  requireDataFile(root, `java/paper-api-surfaces/${paper.latest.minecraftVersion}.json`, messages);
  try {
    getPaperApiSurface(paper.latest.minecraftVersion);
  } catch (error) {
    messages.push(
      `latest Paper API surface must validate: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  }

  return {
    ok: messages.length === 0,
    messages,
  };
}

function printHelp(): void {
  console.log(`minecraft-skills-maintainer

Usage:
  minecraft-skills-maintainer validate
  minecraft-skills-maintainer audit-current-sources
  minecraft-skills-maintainer package-smoke [--keep-temp]
  minecraft-skills-maintainer ingest-java-manifest --input <manifest.json> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-detail --version-json <version.json> [--version-json-url <url>] [--client-jar <client.jar>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-java-version-details [--skip-client-jars] [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer generate-java-reports --server-jar <server.jar> --work-dir <dir> --output-dir <dir> [--java-bin <java>]
  minecraft-skills-maintainer ingest-java-reports --version <version> --reports-dir <generated/reports> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-project --project-json <project.json> --latest-builds-json <builds.json> [--java-latest <version>] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-builds [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-api-indexes [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-paper-api-surfaces [--version <paper-version>] [--retrieved-at <iso>]
  minecraft-skills-maintainer materialize-version-details
  minecraft-skills-maintainer ingest-vanilla-inventory --version <version> --client-jar <client.jar> --server-jar <server.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-vanilla-inventories [--force] [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-datapack-schema --version <version> --server-jar <server.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models --version <version> --client-jar <client.jar> [--retrieved-at <iso>]
  minecraft-skills-maintainer ingest-resourcepack-models-all [--force] [--retrieved-at <iso>]

Commands:
  validate              Validate checked-in data, catalog, and generated skills.
  audit-current-sources Compare bundled latest Java/Paper data with Mojang and PaperMC APIs.
  package-smoke         Pack public packages, install them in a temp project, and smoke-test imports/bins.
  ingest-java-manifest  Generate Java 1.13+ release index from Mojang version manifest.
  ingest-java-version-detail
                        Generate detail JSON from Mojang version JSON and optional client jar.
  ingest-java-version-details
                        Download and generate missing detail JSON for all indexed Java releases.
  generate-java-reports
                        Run Mojang data generator reports from a server jar.
  ingest-java-reports   Generate compact report summary and command path index from server reports.
  ingest-paper-project
                        Generate Paper plugin support and event search data from PaperMC API JSON.
  ingest-paper-builds  Download latest build summaries for all bundled Paper-supported versions.
  ingest-paper-api-indexes
                        Download Paper Javadocs package indexes for supported versions.
  ingest-paper-api-surfaces
                        Download Paper Javadocs type/member search indexes.
  materialize-version-details
                        Write derived domain coverage facts into checked-in version detail JSON.
  ingest-vanilla-inventory
                        Generate compact inventory for vanilla client assets and server data.
  ingest-vanilla-inventories
                        Download and generate missing vanilla inventories for all indexed Java releases.
  ingest-datapack-schema
                        Generate observed vanilla datapack JSON field-shape surface from a server jar.
  ingest-resourcepack-models
                        Generate compact resource pack model summary from a client jar.
  ingest-resourcepack-models-all
                        Download and generate missing resource pack model summaries for all indexed Java releases.`);
}

function readOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index === -1) {
    return undefined;
  }
  return args[index + 1];
}

function ingestJavaManifest(args: string[]): void {
  const input = readOption(args, "--input");
  if (!input) {
    throw new Error("ingest-java-manifest requires --input <manifest.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const manifest = JSON.parse(readFileSync(input, "utf8")) as unknown;
  const versionIndex = buildJavaVersionIndex(manifest, retrievedAt);
  const root = findRepositoryRoot();
  const output = join(root, "packages/data/data/java/versions.json");
  writeFileSync(output, `${JSON.stringify(versionIndex, null, 2)}\n`);
  console.log(`wrote ${versionIndex.versions.length} Java 1.13+ releases to ${output}`);
}

function ingestJavaVersionDetail(args: string[]): void {
  const versionJsonPath = readOption(args, "--version-json");
  if (!versionJsonPath) {
    throw new Error("ingest-java-version-detail requires --version-json <version.json>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  const versionJsonUrl = readOption(args, "--version-json-url");
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const options: {
    versionJsonPath: string;
    clientJarPath?: string;
    versionJsonUrl?: string;
    retrievedAt: string;
  } = {
    versionJsonPath,
    retrievedAt,
  };
  if (clientJarPath) {
    options.clientJarPath = clientJarPath;
  }
  if (versionJsonUrl) {
    options.versionJsonUrl = versionJsonUrl;
  }
  const detail = buildJavaVersionDetail(options);
  const root = findRepositoryRoot();
  const output = join(root, `packages/data/data/java/version-details/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(detail, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} detail to ${output}`);
}

async function ingestAllJavaVersionDetails(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestJavaVersionDetails({
    root,
    retrievedAt,
    includeClientJars: !args.includes("--skip-client-jars"),
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java version detail files`);
}

function ingestJavaReports(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-java-reports requires --version <version>");
  }
  const reportsDir = readOption(args, "--reports-dir");
  if (!reportsDir) {
    throw new Error("ingest-java-reports requires --reports-dir <generated/reports>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildJavaReportsSummary({
    version: detail.version,
    reportsDir,
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  writeJavaReportsSummary({
    root,
    version: detail.version,
    ...summary,
  });
  console.log(`wrote Java ${detail.version} reports summary and command paths`);
}

function generateReports(args: string[]): void {
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("generate-java-reports requires --server-jar <server.jar>");
  }
  const workDir = readOption(args, "--work-dir");
  if (!workDir) {
    throw new Error("generate-java-reports requires --work-dir <dir>");
  }
  const outputDir = readOption(args, "--output-dir");
  if (!outputDir) {
    throw new Error("generate-java-reports requires --output-dir <dir>");
  }
  generateJavaReports({
    javaBin: readOption(args, "--java-bin") ?? "java",
    serverJarPath,
    workDir,
    outputDir,
  });
  console.log(`wrote generated Java reports to ${outputDir}`);
}

function ingestPaperProject(args: string[]): void {
  const projectJsonPath = readOption(args, "--project-json");
  if (!projectJsonPath) {
    throw new Error("ingest-paper-project requires --project-json <project.json>");
  }
  const latestBuildsJsonPath = readOption(args, "--latest-builds-json");
  if (!latestBuildsJsonPath) {
    throw new Error("ingest-paper-project requires --latest-builds-json <builds.json>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const latest = getVersionDetail("java", readOption(args, "--java-latest") ?? "latest");
  const paper = buildPaperPluginData({
    projectJson: JSON.parse(readFileSync(projectJsonPath, "utf8")) as unknown,
    latestBuildsJson: JSON.parse(readFileSync(latestBuildsJsonPath, "utf8")) as unknown,
    javaLatest: latest.version,
    retrievedAt,
  });
  const output = join(root, "packages/data/data/java/paper.json");
  writeFileSync(output, `${JSON.stringify(paper, null, 2)}\n`);
  console.log(`wrote Paper plugin data to ${output}`);
}

async function ingestAllPaperBuilds(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperBuilds({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper version build summaries`);
}

async function ingestAllPaperApiIndexes(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestPaperApiIndexes({
    root,
    retrievedAt,
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper API package index files`);
}

async function ingestAllPaperApiSurfaces(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const onlyVersion = readOption(args, "--version");
  const written = await ingestPaperApiSurfaces({
    root,
    retrievedAt,
    ...(onlyVersion ? { onlyVersion } : {}),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Paper API surface files`);
}

function readDownloadUrl(downloads: Record<string, unknown>, key: string): string {
  const download = downloads[key];
  if (download && typeof download === "object" && "url" in download) {
    const url = (download as { url: unknown }).url;
    if (typeof url === "string") {
      return url;
    }
  }
  throw new Error(`Version detail does not include downloads.${key}.url`);
}

function writeVanillaPathIndex(root: string, version: string, paths: VanillaPathIndex): void {
  const outputRoot = join(root, "packages/data/data/java/vanilla-paths");
  mkdirSync(outputRoot, { recursive: true });
  writeFileSync(
    join(outputRoot, `${version}.resourcepack.txt`),
    `${paths.resourcepack.join("\n")}\n`,
  );
  writeFileSync(join(outputRoot, `${version}.datapack.txt`), `${paths.datapack.join("\n")}\n`);
}

function ingestVanillaInventory(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-vanilla-inventory requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-vanilla-inventory requires --client-jar <client.jar>");
  }
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("ingest-vanilla-inventory requires --server-jar <server.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const { inventory, paths } = buildVanillaData({
    version: detail.version,
    clientJarPath,
    serverJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  const output = join(root, `packages/data/data/java/vanilla-inventories/${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(inventory, null, 2)}\n`);
  writeVanillaPathIndex(root, detail.version, paths);
  console.log(`wrote Java ${detail.version} vanilla inventory to ${output}`);
}

function ingestDatapackSchema(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-datapack-schema requires --version <version>");
  }
  const serverJarPath = readOption(args, "--server-jar");
  if (!serverJarPath) {
    throw new Error("ingest-datapack-schema requires --server-jar <server.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const surface = buildObservedDatapackSchemaSurface({
    version: detail.version,
    serverJarPath,
    serverJarUrl: readDownloadUrl(detail.downloads, "server"),
    retrievedAt,
  });
  const output = writeObservedDatapackSchemaSurface({ root, surface });
  console.log(`wrote Java ${detail.version} observed datapack schema surface to ${output}`);
}

async function ingestAllVanillaInventories(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestVanillaInventories({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java vanilla inventory files`);
}

function ingestResourcepackModels(args: string[]): void {
  const version = readOption(args, "--version");
  if (!version) {
    throw new Error("ingest-resourcepack-models requires --version <version>");
  }
  const clientJarPath = readOption(args, "--client-jar");
  if (!clientJarPath) {
    throw new Error("ingest-resourcepack-models requires --client-jar <client.jar>");
  }
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const root = findRepositoryRoot();
  const detail = getVersionDetail("java", version);
  const summary = buildResourcepackModelSummary({
    version: detail.version,
    clientJarPath,
    clientJarUrl: readDownloadUrl(detail.downloads, "client"),
    retrievedAt,
  });
  const outputRoot = join(root, "packages/data/data/java/resourcepack-models");
  mkdirSync(outputRoot, { recursive: true });
  const output = join(outputRoot, `${detail.version}.json`);
  writeFileSync(output, `${JSON.stringify(summary, null, 2)}\n`);
  console.log(`wrote Java ${detail.version} resourcepack model summary to ${output}`);
}

async function ingestAllResourcepackModels(args: string[]): Promise<void> {
  const root = findRepositoryRoot();
  const retrievedAt = readOption(args, "--retrieved-at") ?? new Date().toISOString();
  const written = await ingestResourcepackModelSummaries({
    root,
    retrievedAt,
    force: args.includes("--force"),
    log: (message) => console.log(message),
  });
  console.log(`wrote ${written} Java resourcepack model summary files`);
}

export async function runMaintainerCli(argv: string[]): Promise<number> {
  const [command] = argv;
  if (!command || command === "help" || command === "--help" || command === "-h") {
    printHelp();
    return 0;
  }

  try {
    if (command === "audit-current-sources") {
      const result = await auditCurrentSources();
      console.log(JSON.stringify(result, null, 2));
      return result.ok ? 0 : 1;
    }

    if (command === "package-smoke") {
      const result = runPackageSmoke({
        root: findRepositoryRoot(),
        keepTemp: argv.includes("--keep-temp"),
      });
      console.log(JSON.stringify(result, null, 2));
      return 0;
    }

    if (command === "ingest-java-manifest") {
      ingestJavaManifest(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-detail") {
      ingestJavaVersionDetail(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-version-details") {
      await ingestAllJavaVersionDetails(argv.slice(1));
      return 0;
    }

    if (command === "ingest-java-reports") {
      ingestJavaReports(argv.slice(1));
      return 0;
    }

    if (command === "generate-java-reports") {
      generateReports(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-project") {
      ingestPaperProject(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-builds") {
      await ingestAllPaperBuilds(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-api-indexes") {
      await ingestAllPaperApiIndexes(argv.slice(1));
      return 0;
    }

    if (command === "ingest-paper-api-surfaces") {
      await ingestAllPaperApiSurfaces(argv.slice(1));
      return 0;
    }

    if (command === "materialize-version-details") {
      const root = findRepositoryRoot();
      const written = materializeVersionDetails(root);
      console.log(`wrote ${written} Java version detail files`);
      return 0;
    }

    if (command === "ingest-vanilla-inventory") {
      ingestVanillaInventory(argv.slice(1));
      return 0;
    }

    if (command === "ingest-vanilla-inventories") {
      await ingestAllVanillaInventories(argv.slice(1));
      return 0;
    }

    if (command === "ingest-datapack-schema") {
      ingestDatapackSchema(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models") {
      ingestResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command === "ingest-resourcepack-models-all") {
      await ingestAllResourcepackModels(argv.slice(1));
      return 0;
    }

    if (command !== "validate") {
      throw new Error(`Unknown command: ${command}`);
    }

    const result = validateRepository();
    if (!result.ok) {
      for (const message of result.messages) {
        console.error(message);
      }
      return 1;
    }
    console.log("minecraft-skills repository validation passed");
    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (isDirectRun(import.meta.url)) {
  process.exitCode = await runMaintainerCli(process.argv.slice(2));
}
